name: Elixir CI

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.18.4"]
        otp: ["27"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-flags: --all-warnings --warnings-as-errors

      - name: Run Tests
        run: mix test
        if: always()
