name: Elixir CI

on:
  push:

permissions:
  contents: read

jobs:
  code-quality:
    name: Formatting, unused deps
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.18.4"]
        otp: ["27"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-flags: --all-warnings --warnings-as-errors

      - name: Check for unused deps
        run: mix deps.unlock --check-unused

      - name: Check code formatting
        run: mix format --check-formatted
        # Check formatting even if there were unused deps so that
        # we give devs as much feedback as possible & save some time.
        if: always()
